version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nodejs-app:
    build: .
    environment:
      DB_HOST: mysql
      DB_USER: myuser
      DB_PASSWORD: userpassword
      DB_NAME: mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:
